name: Unit Tests

on:
  push:
    paths:
      - "**.php"
      - ".github/workflows/unit-tests.yml"
      - "phpunit.xml.dist"
    branches:
      - main
  pull_request:
    paths:
      - "**.php"
      - ".github/workflows/unit-tests.yml"
      - "phpunit.xml.dist"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  supported-versions-matrix:
    name: Supported PHP Versions Matrix
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.supported-versions-matrix.outputs.version }}
    steps:
      - name: Check out the repository to the runner
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2
      - id: supported-versions-matrix
        uses: WyriHaximus/github-action-composer-php-versions-in-range@v1

  tests:
    name: "Unit Tests - PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    needs:
      - supported-versions-matrix
    env:
      extensions: apcu,intl,mbstring,iconv
    strategy:
      matrix:
        php: ${{ fromJson(needs.supported-versions-matrix.outputs.version) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: date.timezone=UTC,memory_limit=-1,session.gc_probability=0,apc.enable_cli=1,zend.assertions=1
          php-version: "${{ matrix.php }}"
          extensions: "${{ matrix.extensions || env.extensions }}"
      - name: Composer install
        uses: ramsey/composer-install@v3
      - name: Configure phpunit github matchers
        uses: mheap/phpunit-matcher-action@v1
      - name: Run phpunit
        run: ./vendor/bin/phpunit --teamcity
